workflows:
  native-android:
    name: Android Workflow
    max_build_duration: 15
    instance_type: mac_mini_m1
    environment:
      groups:
        - keystore_credentials
        - app_store_credentials
      vars:
        PACKAGE_NAME: "io.codemagic.ermalapp"
    scripts:
      - name: Get Flutter Packages
        script: flutter packages pub get
      - name: Build apk
        script: flutter build apk --release
      - name: Build android
        script: flutter build android
      - name: Set up key properties
        script: |
          cat >> "$CM_BUILD_DIR/android/key.properties" << EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=$CM_KEYSTORE_PATH
          EOF
  
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - user_1@example.com
          - e.a.mateli@gmail.com

